name: Fragman Pipeline

on:
  repository_dispatch:
    types: [fragman_request]

jobs:
  fragman:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Ã§ek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Test echo
        run: |
          echo "EVENT TETIKLENDI"
          cat $GITHUB_EVENT_PATH
