name: Fragman Pipeline

on:
  repository_dispatch:
    types: [fragman_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ðŸ“¥ Repo Checkout
        uses: actions/checkout@v4

      - name: ðŸ§± FFmpeg ve yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade yt-dlp requests

      - name: ðŸŽ¬ Fragman Ãœret
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python fragman.py
