name: Fragman Pipeline

on:
  repository_dispatch:
    types: [fragman_request]

jobs:
  fragman:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Repo Checkout
        uses: actions/checkout@v4

      - name: ğŸ Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Paketler
        run: pip install requests

      - name: ğŸ¬ Fragman Ãœret
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python fragman.py
