name: YouTube TTS Pipeline

on:
  repository_dispatch:
    types: [tts_request]

jobs:
  tts:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: FFmpeg kur
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

       - name: Bağımlılıkları kur
        run: |
         sudo apt update
         sudo apt install -y ffmpeg
         pip install edge-tts requests

      - name: TTS üret ve gönder
        run: |
          python tts.py
